version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_CONNECTION_URL: ${DATABASE_URL}
      USER_NAME: ${DATABASE_USERNAME}
      PASSWORD: ${DATABASE_PASSWORD}
      FILE_STORAGE_DIR: ${FILE_STORAGE_DIR}
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
